#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_3,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           leftMotor,     tmotorVex393_HBridge, openLoop, driveLeft)
#pragma config(Motor,  port2,           clawMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           highMotor,     tmotorVex393_MC29, openLoop, encoderPort, I2C_1)
#pragma config(Motor,  port4,           chevronMotor,  tmotorVex393_MC29, openLoop, encoderPort, I2C_2)
#pragma config(Motor,  port5,           trackMotor,    tmotorVex393_MC29, openLoop, encoderPort, I2C_3)
#pragma config(Motor,  port6,           MGMotorL,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           MGMotorR,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          rightMotor,    tmotorVex393_HBridge, openLoop, driveRight)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
//#include "Vex_Competition_Includes.c"


/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks
	// running between Autonomous and Driver controlled modes. You will need to
	// manage all user created tasks if set to false.
	//bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
	// ..........................................................................
	// Insert user code here.
	// ..........................................................................

	// Remove this function call once you have "real" code.
	//  AutonomousCodePlaceholderForTesting();
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task main()
{
	// User control code here, inside the loop
	int joy_xl;
	int joy_yl;
	int joy_xr;
	int joy_yr;
	int tolleranz = 10;

	nMotorEncoder[highMotor] = 0;
	nMotorEncoder[chevronMotor] = 0;

	int highMotorEncMin = -500;
	int highMotorEncMax =  500;

	int chevronMotorEncMin = -500;
	int chevronMotorEncMax =  500;

	int direction = 0;

	int leftPower = 0;
	int rightPower = 0;

	while(true){
		joy_xl = vexRT[Ch4];
		joy_yl = vexRT[Ch3];
		joy_xr = vexRT[Ch1];
		joy_yr = vexRT[Ch2];

		direction = 0;

		leftPower = 0;
		rightPower = 0;

		//Movement
		{
			if((joy_yl > tolleranz)  || (joy_yl < -tolleranz))		//Backward and Forward Movement
			{
				leftPower 	= leftPower 	+ (0);
				rightPower 	= rightPower 	+ (0);
				}else{
				leftPower = leftPower +(joy_yl /4);
				rightPower = leftPower;
			}

			if((joy_xl > tolleranz) || (joy_xl < -tolleranz))	//Right Left Movement
			{
				leftPower = leftPower 	+(0);
				rightPower = rightPower +(0);
				}else if(joy_xl > 0){
				leftPower = leftPower +(joy_xl/4);
				rightPower = rightPower -(joy_xl/4);
				}else{
				leftPower = leftPower -(joy_xl/4);
				rightPower = rightPower +(joy_xl/4);
			}
			motor[leftMotor] = leftPower;											//Change speed of Motors
			motor[rightPower] = rightPower;
		}

		//Mobile Goal	Btn Gruppe 5
		{
			if(vexRT[Btn5U] == 1){
				motor[MGMotorL] = 84;
				motor[MGMotorR] = 84;
				wait1Msec(250);
			}
			else if(vexRT[Btn5D] == 1){
				motor[MGMotorL] = -(84);
				motor[MGMotorR] = -(84);
				wait1Msec(250);
			}
		}

		//Winkel Ch1
		{
			direction = 0;
			if(nMotorEncoder[chevronMotor] < chevronMotorEncMin){
				if(vexRT[Ch1] > 0){
					direction = 1;
				}
				}else if(nMotorEncoder[chevronMotor] > chevronMotorEncMax){
				if(vexRT[Ch1] < 0){
					direction = -1;
				}
			}
			motor[chevronMotor] = direction * 63;
		}


		//Lift UP/DOWN Ch2
		{
			direction = 0;
			if(nMotorEncoder[highMotor] < highMotorEncMin){
				if(vexRT[Ch2] > 0){
					direction = 1;
				}
				}else if(nMotorEncoder[highMotor] > highMotorEncMax){
				if(vexRT[Ch2] < 0){
					direction = -1;
				}
			}
			motor[highMotor] = direction * 63;
		}

		//Claw Btn Gruppe 6
		{
			direction = 0;
			if(vexRT[Btn6U] == 1)
			{
				direction = 1;
			}
			else if(vexRT[Btn6D] == 1)
			{
				direction = -1;
			}
			motor[clawMotor] = direction * 127;
		}


	}
}
// This is the main execution loop for the user control program.
// Each time through the loop your program should update motor + servo
// values based on feedback from the joysticks.

// ........................................................................
// Insert user code here. This is where you use the joystick values to
// update your motors, etc.
// ........................................................................
