#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_3,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           leftMotor,     tmotorVex393_HBridge, openLoop, driveLeft)
#pragma config(Motor,  port2,           clawMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           highMotor,     tmotorVex393_MC29, openLoop, encoderPort, I2C_1)
#pragma config(Motor,  port4,           chevronMotor,  tmotorVex393_MC29, openLoop, encoderPort, I2C_2)
#pragma config(Motor,  port5,           trackMotor,    tmotorVex393_MC29, openLoop, encoderPort, I2C_3)
#pragma config(Motor,  port10,          rightMotor,    tmotorVex393_HBridge, openLoop, driveRight)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"


/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks
	// running between Autonomous and Driver controlled modes. You will need to
	// manage all user created tasks if set to false.
	//bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
	// ..........................................................................
	// Insert user code here.
	// ..........................................................................

	// Remove this function call once you have "real" code.
	//  AutonomousCodePlaceholderForTesting();
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

void clawOpenClose(bool richtung){
	int richtungAus;
	if(!richtung){
		richtungAus = -1;
	}
	else{
		richtungAus = 1;
	}
	motor[clawMotor] = richtungAus * 127;
}

task main()
{
	// User control code here, inside the loop
	int joy_xl;
	int joy_yl;
	int tolleranz = 10;

	// This is the main execution loop for the user control program.
	// Each time through the loop your program should update motor + servo
	// values based on feedback from the joysticks.

	// ........................................................................
	// Insert user code here. This is where you use the joystick values to
	// update your motors, etc.
	// ........................................................................



	while(true){
		joy_xl = vexRT[Ch4];
		joy_yl = vexRT[Ch3];
		joy_xr = vexRT[Ch1];
		joy_xl = vexRT[Ch2];
		if((abs(joy_xl) > tolleranz) && (abs(joy_yl) > tolleranz) && (joy_yl > 0))
		{
			motor[leftMotor]  = (joy_yl - joy_xl)/2;
			motor[rightMotor] = (joy_yl + joy_xl)/2;
		}
		else if((abs(joy_xl) > tolleranz) && (abs(joy_yl) > tolleranz) && (joy_yl < 0))
		{
			motor[leftMotor]  = (joy_yl + joy_xl)/2;
			motor[rightMotor] = (joy_yl - joy_xl)/2;
		}
		else if((abs(joy_xl) > tolleranz) && (abs(joy_yl) < tolleranz))
		{
			motor[leftMotor]  = joy_xl;
			motor[rightMotor] = (-1 * joy_xl);}
		// Ab hier neuer Code
		else if((abs(joy_xr) > 127))
		{
			motor[trackMotor] = joy_xr;
			motor[trackMotor] =
		}
		// Neuer Code ende
		else
		{
			motor[leftMotor]  = 0;
			motor[rightMotor] = 0;
		}
		if(vexRT[Btn6U] == 1)
		{
			clawOpenClose(1);
		}
		else if(vexRT[Btn6D] == 1)
		{
			clawOpenClose(0);
		}
	}
}
